language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

matrix:
  fast_finish: true

before_script:
  - curl -s http://getcomposer.org/installer | php -- --quiet
  - php composer.phar install --dev --prefer-source

script: bin/phpunit
